### ISSUE TITLE
Can't find settings (button)?

### ISSUE THREAD

**Issue by drone1** [nclarius/tile-gaps#10]
Hey! So excited to start using this but after installation I can't seem to find the settings under System Settings -> Window Management -> KWin Scripts. Looks like this:

![image](https://user-images.githubusercontent.com/6324796/165409104-917796aa-8032-4bae-a515-244f06d8d4b2.png)

Shouldn't I be seeing a button for settings here, or is it somewhere else? Not sure if it's a bug or not. I'm on Ubuntu 21.10, Plasma 5.22.5. Thanks a lot.

**Comment by nclarius** [comment]
Have you followed the instructions in the readme?

**Comment by drone1** [comment]
Ooops. I thought my Plasma version was more recent than it is. Fixed with those commands, thanks.
