### ISSUE TITLE
Windows shrinking

### ISSUE THREAD

**Issue by Akselmo** [nclarius/tile-gaps#11]
Hi, there's a bug when this script is used in Wayland with two monitors:

If I place two vertically full size windows next to each other, the windows start fighting for space and the rightmost window starts shrinking continuously.

I tried to take a video of it but it happens very randomly.

**Comment by nclarius** [comment]
This sounds like a Wayland-independent issue which should have been fixed a few versions ago. Which version of the script are you running? (Find out with the info button in the KWin script system settings.)

If you are using the most recent version and the problem persists, I'll need some debug information to figure out where it's going wrong. Unfortunately logging sometimes may require some detours to get working on Wayland. Could you please run the following in a terminal:
```
export QT_LOGGING_RULES='*=false; js=true; kwin_scripting=true'
kwriteconfig5 --file kwinrc --group Script-test --key debugMode true
kwriteconfig5 --file kwinrc --group Script-test --key fullDebugMode true
```
then log out and in again, and tell me whether you are getting any output at all for
```
journalctl -g "tilegaps" -f
```
when you move some windows?

**Comment by nclarius** [comment]
Before we continue, could you please verify that you have the current version (6.15) installed, because a bug like this was fixed a few versions back.

If this is still present with the newest version: I think I understand what behavior you're getting, but I can't reproduce it on my own multi-monitor setup, so I need to look into the log to figure out what's going on.

Please try the following:
```
echo 'export QT_LOGGING_RULES="kwin_*.debug=true"' >> ~/.bash_profile
kwriteconfig5 --file startkderc --group General --key systemdBoot true
```
Then log out and in again and try the journalctl command again; are you getting anything now?

If these changes are causing problems, you can revert them by running the same commands again with `false`.

**Comment by nclarius** [comment]
If you do get output from the journal now: 

Wait for the bug to occur, then do

```
journalctl -g "tilegaps:" "--since 15 min ago" --until "5 min ago" > tilegaps.log
```
(with the appropriate time frame, as narrow as possible).

The log file will contain window titles, so make sure these contain no sensitive information.

Then upload the contents of the file here.

**Comment by Akselmo** [comment]
Hey, sorry it's been a while. If I have time I try to test this this weekend.. 

Just wanted to comment that I havent forgotten this :)

**Comment by Akselmo** [comment]
Welp, sorry it took so long. I managed to get the bug happen, but journal isnt logging anything. I am using the one from this repo, i cloned the repo and used install.sh on master branch

**Comment by nclarius** [comment]
> journal isnt logging anything even after following your directions. 

Hm. One more possibility I found which you could try: Open `kdebugsettings`, and make sure "KWin Scripting" is set to "Full Debug".

> After running the tile-gaps for a day or so, I noticed that the bug now only appears when the latte-dock panel i have, goes from floating to not-floating. 

This is a useful hypothesis, I'll try to reproduce it.

**Comment by Akselmo** [comment]
> Open kdebugsettings, and make sure "KWin Scripting" is set to "Full Debug".

No dice. :(

This is all I'm getting

```
journalctl -g "tilegaps" --since=yesterday
-- Boot f6a1040c93ef496eaf552f923ce2fbbe --
-- Boot 6cc38cc1cf2741bda866be0adafde7db --
Jun 15 21:44:06 fedora systemsettings[39389]: unable to delete file  "/home/akseli/.local/share/kwin/scripts/tilegaps" . file does not exist.
-- Boot b99fddd9e74747c29c8295eef83f5f24 --
-- Boot 232997e707724b8581ed0850eed6ba1f --
-- Boot 0a2b53f7521f411aa48f055c9bbf8bb2 --
-- Boot e949ffdb3bfb4700b9f20983536bc427 --
-- Boot 51fba15e621c45f78a6d14d65f10ca9d --
-- Boot 51c6cafca5344cedbd30f59ddb27adaa --
```

**Comment by nclarius** [comment]
I'm sorry, but I am still not able to reproduce it and don't have an idea what it could be. I'm also at my wit's end with the non-functioning logging. I'm afraid you'll have to live with the bug until further notice. Thank you for your help up to here!

I just published a new version integrating the gaps better with the floating panels introduced with the newest Plasma release.

**Comment by Akselmo** [comment]
Ah well, thank you for trying. I can try to see if I could fix it myself when I have time.

**Comment by Akselmo** [comment]
Hey!! Good news, I managed to get you some logs!

I had to set the `export QT_LOGGING_RULES="kwin_*.debug=true"` to `/etc/environment/` and now I can see the logs!

Here you go:
[tilegaps.log](https://github.com/nclarius/tile-gaps/files/8934262/tilegaps.log)

What I was exactly doing was moving a window to the rightmost half of my (last) second monitor. When it snaps to a window-x that is quarter tiled to top-left on that monitor, and i tile the new window-y full half on the right side of it, window-y snaps to window-x and starts resizing down from the right side.

One thing I am wondering about is that does the script ignore widgets on desktop? Since I have widgets on the very right edge of my monitor.

**Comment by nclarius** [comment]
Yay!  

That is indeed a logic error; good catch! I fixed it with the most resent update; please test whether this solves the problem.

**Comment by Akselmo** [comment]
This solved the shrinking problem (however it reintroduces itself if i have any floating panels checked, but i can live without that), but now there's overlap between windows, and the window still goes a bit over the right edge of screen.

![image](https://user-images.githubusercontent.com/13801236/175239197-5dc41f61-8965-43ef-bd7d-f43c6367259e.png)

**Comment by nclarius** [comment]
Sorry for the long inactivity. Please check if the newest update fixes the bug for you.

**Comment by Akselmo** [comment]
So far so good, I'll keep testing over longer period and report if theres any issues. Thanks!
