### ISSUE TITLE
Incompatible with Flupp/sticky-window-snapping

### ISSUE THREAD

**Issue by fischer-felix** [nclarius/tile-gaps#12]
I installed Window Gaps and also have [Sticky Window Snapping](https://github.com/Flupp/sticky-window-snapping) installed, however the window gaps seem to have broken its functionality. It makes it so that whenever two windows are touching, and you resize the touching side, both of them are moved. Now only one window is moving.
I don't know what side is causing the problem, hence opening an issue on both projects.

**Comment by nclarius** [comment]
Have you followed the instructions in the readme?

**Comment by fischer-felix** [comment]
Sorry, I had not properly read the README, so I had not followed them, however setting the threshold did not fix the issue. 
Thankfully, Flupp pointed me to your [PR](https://github.com/Flupp/sticky-window-snapping/pull/16) to fix this problem, so I installed your fork, and it works flawlessly!
