### ISSUE TITLE
Gaps disappearing when changing size

### ISSUE THREAD

**Issue by gigaturbo** [nclarius/tile-gaps#14]
The gaps works well when adding a few windows but the gaps disappear when resizing or when there are many windows

When it works:
![p0](https://user-images.githubusercontent.com/11806309/175406050-6e241915-c257-4b4c-8a77-816fc0215850.png)

After resizing windows:
![p1](https://user-images.githubusercontent.com/11806309/175406023-0056c338-31dc-4260-a9b3-d29034f65395.png)

I'm using version 7.1

**Comment by nclarius** [comment]
Thanks for the report. It should be fixed with the update I just released. If not, please reopen this thread.
