### ISSUE TITLE
Losing borders (window decorations)

### ISSUE THREAD

**Issue by danielkrajnik** [nclarius/tile-gaps#17]
Borders (window decorations) lost when "snapping" (Super Key + arrows keys) windows.

OS: Ubuntu 22.04.1 LTS x86_64
WM Theme: Breeze
Theme: Breeze [GTK2/3]

Oversized borders to illustrate:

![image](https://user-images.githubusercontent.com/15096799/191014937-702f0026-cc3f-4054-9575-3ba645cc5242.png)

**Comment by nclarius** [comment]
I believe this is due to a misleadingly worded configuration option in the Breeze decoration.

Try System Settings > Appearance > Window Decorations > Breeze: edit button > General > Allow resizing maximized windows from window edges: enable.

**Comment by nclarius** [comment]
I'm assuming this solvd this issue. If not, please reopen the thread.
