### ISSUE TITLE
No gaps when using windows in a vertical 2x1 orientation

### ISSUE THREAD

**Issue by TonyTwoStep** [nclarius/tile-gaps#2]
I've noticed that no gap is added when tiling two windows in a 2x1 orientation, split horizontally:
Example using a portrait monitor:
<img src="https://user-images.githubusercontent.com/43851175/138214771-260c6dd5-f2cb-4b3b-9600-4a83a83033b8.png" width="50%">

While this issue affects both portrait and landscape monitor orientations alike, users of a vertically oriented monitor commonly use this type of layout.

It's worth noting that gaps are properly displayed in 1x2 and 2x2 tiling layouts, just this one is missing the gaps.
Here's a 2x2 layout with working gaps:
<img src="https://user-images.githubusercontent.com/43851175/138215544-24a5d678-367d-4d9b-a7dc-e79c142fc054.png" width="50%">

Lastly, this app is great, thank you for making it,

**Comment by nclarius** [comment]
Oh, I understand now. I had overlooked that layout possibility; thanks for pointing it out. It should be fixed now; please reinstall and tell me if it works now.
