### ISSUE TITLE
All Windows are snapping in the Screen center.

### ISSUE THREAD

**Issue by dono110** [nclarius/tile-gaps#21]
On version 7.1, all windows are snapping in the center of the Screen. 
Center snap zone is disabled in system settings.

Configuration:
![image](https://user-images.githubusercontent.com/59128961/203929947-cb0f0aaf-57c5-4289-b1b0-544dc49da896.png)

**Comment by nclarius** [comment]
Thanks for the report. I just released an update that should fix this bug. If not, please repoen this issue.
