### ISSUE TITLE
No config options, fix in readme not working

### ISSUE THREAD

**Issue by jonseppanen** [nclarius/tile-gaps#6]
As stated, latest arch/endeavour

No config options, even when applying the fix in readme.

**Comment by nclarius** [comment]
Even after logging out and in again?

**Comment by jonseppanen** [comment]
After logout it shows up but says "Plugin does not provide configuration file in expected location" when clicked.

**Comment by nclarius** [comment]
That's strange.

  Do the flowing files exist?
 `~/.local/share/kwin/scripts/tilegaps/contents/config/main.xml`  
 `~/.local/share/kwin/scripts/tilegaps/contents/confi.ui`  
`~/.config/kwinrc`

**Comment by nclarius** [comment]
Looks like https://bugs.kde.org/show_bug.cgi?id=444378 https://forum.garudalinux.org/t/bismuth-settings-fail/13236.

**Comment by nclarius** [comment]
While the problem persists, a workaround might be to edit the configuration directly:

In `~/.config/kwinrc`, overwrite or else append:
```
[Script-tilegaps]
gapTop=12
gapLeft=12
gapRight=12
gapBottom=12
gapMid=12
includeMaximized=false
excludeMode=true
excludedApps=
includeMode=false
includedApps=
```

**Comment by nclarius** [comment]
With 5.24 I am now experiencing the same problem. There is currently no working fix that I know of.

**Comment by nclarius** [comment]
This issue has been fixed in KWin now, so I assume the problem is solved. If not, please reopen.
